### PR TITLE
Refactoring the primer/spacing plugin to better match results

### PR DESCRIPTION
**Pull request by jonrohan**
This PR focuses on a refactor/rewrite of our `primer/spacing` lint rule. The main thing lacking in our old rule was that when someone used a variable and then a number, the linter would miss it. 

Example:

```scss
// Not caught by linter
.foo {
  margin: $spacer-1 3px;
}
```

It also was a fuzzy match before, so `$spacer-not-a-real-spacer` would count as a valid primer/css spacer. Now they are exact matches.

I ran this plugin update on `primer/css` and the `github/github` codebase, here's the new errors it found. @primer/css-reviewers Do you think any of the errors below are aggressive or wrong?

## New lint errors in primer/css

<details>
<summary>Lint output</summary>
<pre>
/Users/jonrohan/Code/@primer/css/src/buttons/button.scss: line 297, col 25, error - Please use a primer spacer variable instead of '1.5em'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/forms/form-control.scss: line 246, col 22, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/forms/form-group.scss: line 243, col 23, error - Please use a primer spacer variable instead of '2px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/labels/mixins.scss: line 9, col 14, error - Please use a primer spacer variable instead of '7px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/labels/mixins.scss: line 18, col 18, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/labels/mixins.scss: line 19, col 17, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/labels/mixins.scss: line 30, col 12, error - Please use a primer spacer variable instead of '0.1667em'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/layout/grid.scss: line 37, col 17, error - Please use a primer spacer variable instead of '-$gutter-width'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/layout/grid.scss: line 38, col 16, error - Please use a primer spacer variable instead of '-$gutter-width'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/layout/grid.scss: line 41, col 20, error - Please use a primer spacer variable instead of '$gutter-width'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/layout/grid.scss: line 42, col 19, error - Please use a primer spacer variable instead of '$gutter-width'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 11, col 44, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 15, col 46, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 17, col 49, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 21, col 50, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 23, col 49, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 28, col 49, error - Please use a primer spacer variable instead of '-$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 30, col 52, error - Please use a primer spacer variable instead of '-$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 34, col 54, error - Please use a primer spacer variable instead of '-$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 36, col 54, error - Please use a primer spacer variable instead of '-$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 43, col 25, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 44, col 24, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 50, col 21, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/margin.scss: line 51, col 24, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/padding.scss: line 11, col 45, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/padding.scss: line 15, col 47, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/padding.scss: line 17, col 49, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/padding.scss: line 19, col 50, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/padding.scss: line 21, col 48, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/padding.scss: line 26, col 26, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/padding.scss: line 27, col 25, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/padding.scss: line 33, col 22, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/utilities/padding.scss: line 34, col 25, error - Please use a primer spacer variable instead of '$size'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/Users/jonrohan/Code/@primer/css/src/marketing/type/typography.scss: line 125, col 17, error - Please use a primer spacer variable instead of '$spacer'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
</pre>
</details>

## New lint errors in github/github

<details>
<summary>Lint output</summary>
<pre>
/workspaces/github/app/assets/stylesheets/lightweight-web-editor.scss: line 9, col 17, error - Please use a primer spacer variable instead of '$spacer-negative-fifty-percent'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/components/pagehead.scss: line 102, col 22, error - Please use a primer spacer variable instead of '15px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/components/pagehead.scss: line 102, col 27, error - Please use a primer spacer variable instead of '11px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/deprecated/select-menu.scss: line 158, col 22, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/deprecated/select-menu.scss: line 251, col 34, error - Please use a primer spacer variable instead of '2px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/deprecated/select-menu.scss: line 324, col 42, error - Please use a primer spacer variable instead of '30px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/deprecated/table-list.scss: line 58, col 22, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/admin/pre-receive-hooks.scss: line 56, col 20, error - Please use a primer spacer variable instead of '$spacer-0'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/gist/snippet.scss: line 78, col 25, error - Please use a primer spacer variable instead of '11px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/large-file-storage.scss: line 23, col 24, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/performance-bar.scss: line 54, col 24, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/performance-bar.scss: line 103, col 26, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/serverstats.scss: line 202, col 24, error - Please use a primer spacer variable instead of '6px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/serverstats.scss: line 257, col 24, error - Please use a primer spacer variable instead of '6px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/site-admin-table.scss: line 30, col 24, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/site-admin.scss: line 27, col 24, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/site-admin.scss: line 274, col 25, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/stafftools.scss: line 18, col 24, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/stafftools.scss: line 552, col 25, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/user.scss: line 60, col 23, error - Please use a primer spacer variable instead of '-10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/user.scss: line 132, col 28, error - Please use a primer spacer variable instead of '20px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/user.scss: line 133, col 27, error - Please use a primer spacer variable instead of '-10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/user.scss: line 326, col 26, error - Please use a primer spacer variable instead of '20px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/staff/user.scss: line 326, col 31, error - Please use a primer spacer variable instead of '30px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/auth.scss: line 319, col 28, error - Please use a primer spacer variable instead of '20px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/blob.scss: line 29, col 22, error - Please use a primer spacer variable instead of '20px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/blob.scss: line 29, col 27, error - Please use a primer spacer variable instead of '5px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/blob.scss: line 29, col 31, error - Please use a primer spacer variable instead of '30px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/hooks.scss: line 285, col 22, error - Please use a primer spacer variable instead of '6px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/hooks.scss: line 285, col 26, error - Please use a primer spacer variable instead of '3px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/integration-installations.scss: line 13, col 24, error - Please replace 64px with spacing variable '$spacer-8'. (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/integration-installations.scss: line 13, col 39, error - Please use a primer spacer variable instead of '30px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/notifications.scss: line 66, col 23, error - Please use a primer spacer variable instead of '20px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/pull-request-review.scss: line 131, col 26, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/pull-request.scss: line 194, col 24, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/settings.scss: line 274, col 24, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/task-lists.scss: line 43, col 12, error - Please use a primer spacer variable instead of '$spacer-0'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/task-lists.scss: line 43, col 22, error - Please use a primer spacer variable instead of '2px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/task-lists.scss: line 161, col 24, error - Please use a primer spacer variable instead of '$spacing-task-item-1'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/task-lists.scss: line 161, col 45, error - Please use a primer spacer variable instead of '$spacer-0'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/task-lists.scss: line 161, col 55, error - Please use a primer spacer variable instead of '$spacing-task-item-3'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/task-lists.scss: line 162, col 13, error - Please use a primer spacer variable instead of '$spacer-0'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/task-lists.scss: line 162, col 24, error - Please use a primer spacer variable instead of '-$spacing-task-item-1'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/task-lists.scss: line 162, col 47, error - Please use a primer spacer variable instead of '$spacer-0'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/task-lists.scss: line 162, col 58, error - Please use a primer spacer variable instead of '-$spacing-task-item-2'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/custom/github/teams.scss: line 163, col 24, error - Please use a primer spacer variable instead of '10px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/marketing/utilities/layout.scss: line 118, col 21, error - Please use a primer spacer variable instead of '-$gutter-width'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/marketing/utilities/layout.scss: line 119, col 20, error - Please use a primer spacer variable instead of '-$gutter-width'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/marketing/utilities/layout.scss: line 122, col 24, error - Please use a primer spacer variable instead of '$gutter-width'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/marketing/utilities/layout.scss: line 123, col 23, error - Please use a primer spacer variable instead of '$gutter-width'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/marketing/readme/base/mixins.scss: line 170, col 18, error - Please use a primer spacer variable instead of '-130px'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
/workspaces/github/app/assets/stylesheets/marketing/readme/views/guides.scss: line 112, col 22, error - Please use a primer spacer variable instead of '$spacer-0'. Consult the primer docs for a suitable replacement. https://primer.style/css/support/spacing (primer/spacing)
</pre>
</details>

### CODE REVIEW

**Comment by langermank** [comment]
Curious about the grid errors 

```@mixin gutters ($gutter-width: $spacer-3) {
  margin-right: -$gutter-width;
  margin-left: -$gutter-width;

  > [class*='col-'] {
    padding-right: $gutter-width !important;
    padding-left: $gutter-width !important;
  }
}
```

Is that just an unusual use case maybe? It doesn't seem to be catching any action-list vars

```
$actionList-item-height-sm: $spacer-2 * 2.5 !default;
$actionList-item-label-line-height: $spacer-2 * 2.5 !default;
$actionList-item-padding-vertical-md: $spacer-2 * 1.25 !default;
$actionList-item-padding-vertical-lg: $spacer-2 * 1.75 !default;
```

So it won't fail if you make a new var that references a spacer var? (I dont think it should, so wanted to check)

**Review by simurai — COMMENTED** [review]
> So it won't fail if you make a new var that references a spacer var? (I dont think it should, so wanted to check)

I'm wondering about that too. I think it **should** fail. Because doing math like:

```
$my-var: $spacer-2 * 1.75 !default;
```

you could get around stylelint by hiding it in a var, but the outputted value doesn't match any of the values in the spacer scale. And to the browser it's the same as using a hardcoded px value.

**Comment by jonrohan** [comment]
The linter never looked at variables being created, so it won't fail on:

```
$my-var: $spacer-2 * 1.75 !default;
```

However what I have written here should fail when any variable that's not a primer/css spacer variable is used for margin or padding. This ensures there's no hiding of the math that's occurring and the resulting spacing size.

**Review by simurai — APPROVED** [review]
> So if someone created a one off variable $my-var like above ☝🏻 , then this code will fail:

Ahh.. Creating variables is fine, but when using them it will fail. Ok, that sounds good to me. 👍

**Pull request merged**
